name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build poetry grpcio-tools protoletariat
        sudo apt install -y protobuf-compiler
    - name: Build package
      run: poetry build
    - name: Delete Platform-Specific Wheel
      run: rm dist/*.whl
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
